In [ ]:
Numpy examples


import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

In [2]:
a = np.arange(0, 10, 0.2)
a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [3]:
a[:5]

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [4]:
a.sum()

245.00000000000003

In [5]:
a.std()

2.8861739379323628

In [6]:
a.cumsum(), a.std(), a.sum()

(array([  0.00000000e+00,   2.00000000e-01,   6.00000000e-01,
          1.20000000e+00,   2.00000000e+00,   3.00000000e+00,
          4.20000000e+00,   5.60000000e+00,   7.20000000e+00,
          9.00000000e+00,   1.10000000e+01,   1.32000000e+01,
          1.56000000e+01,   1.82000000e+01,   2.10000000e+01,
          2.40000000e+01,   2.72000000e+01,   3.06000000e+01,
          3.42000000e+01,   3.80000000e+01,   4.20000000e+01,
          4.62000000e+01,   5.06000000e+01,   5.52000000e+01,
          6.00000000e+01,   6.50000000e+01,   7.02000000e+01,
          7.56000000e+01,   8.12000000e+01,   8.70000000e+01,
          9.30000000e+01,   9.92000000e+01,   1.05600000e+02,
          1.12200000e+02,   1.19000000e+02,   1.26000000e+02,
          1.33200000e+02,   1.40600000e+02,   1.48200000e+02,
          1.56000000e+02,   1.64000000e+02,   1.72200000e+02,
          1.80600000e+02,   1.89200000e+02,   1.98000000e+02,
          2.07000000e+02,   2.16200000e+02,   2.25600000e+02,
        

In [12]:
# vectorized mathematical operations
l = np.arange(0, 10, 1)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
l * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
l ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [15]:
l ** l

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [16]:
np.exp(l)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [17]:
%timeit np.sqrt(2.5)

666 ns ± 9.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [19]:
import math
%timeit math.sqrt(2.5)

105 ns ± 1.43 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [8]:
b = np.array([a, a * 2])
b

array([[  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
          1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
          3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
          5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
          7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
          9. ,   9.2,   9.4,   9.6,   9.8],
       [  0. ,   0.4,   0.8,   1.2,   1.6,   2. ,   2.4,   2.8,   3.2,
          3.6,   4. ,   4.4,   4.8,   5.2,   5.6,   6. ,   6.4,   6.8,
          7.2,   7.6,   8. ,   8.4,   8.8,   9.2,   9.6,  10. ,  10.4,
         10.8,  11.2,  11.6,  12. ,  12.4,  12.8,  13.2,  13.6,  14. ,
         14.4,  14.8,  15.2,  15.6,  16. ,  16.4,  16.8,  17.2,  17.6,
         18. ,  18.4,  18.8,  19.2,  19.6]])

In [9]:
b[0]

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [10]:
b[0,2]

0.40000000000000002

In [12]:
b.sum(axis=0)

array([  0. ,   0.6,   1.2,   1.8,   2.4,   3. ,   3.6,   4.2,   4.8,
         5.4,   6. ,   6.6,   7.2,   7.8,   8.4,   9. ,   9.6,  10.2,
        10.8,  11.4,  12. ,  12.6,  13.2,  13.8,  14.4,  15. ,  15.6,
        16.2,  16.8,  17.4,  18. ,  18.6,  19.2,  19.8,  20.4,  21. ,
        21.6,  22.2,  22.8,  23.4,  24. ,  24.6,  25.2,  25.8,  26.4,
        27. ,  27.6,  28.2,  28.8,  29.4])

In [13]:
b.sum(axis=1)

array([ 245.,  490.])

In [14]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [15]:
c = np.ones((2, 3, 4), dtype='i', order='C') 
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [16]:
np.empty((2, 3, 2))

array([[[  1.63497231e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [17]:
np.empty_like(c)

array([[[33093904,        0,        0,        0],
        [       0,        0,        0,        0],
        [       0,        0,        0,        0]],

       [[       0,        0,        0,        0],
        [       0,        0,        0,        0],
        [       0,        0,        0,        0]]], dtype=int32)

In [18]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.linspace(5, 15, 12)

array([  5.        ,   5.90909091,   6.81818182,   7.72727273,
         8.63636364,   9.54545455,  10.45454545,  11.36363636,
        12.27272727,  13.18181818,  14.09090909,  15.        ])

In [20]:
g = np.arange(15)
g.shape, np.shape(g)

((15,), (15,))

In [24]:
g.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
g.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.resize(g, (2, 5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.resize(g, (5,4))

In [32]:
h = g.reshape(5,3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
np.hstack((h, 2*h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [35]:
np.vstack((h, 0.5*h))

array([[  0. ,   1. ,   2. ],
       [  3. ,   4. ,   5. ],
       [  6. ,   7. ,   8. ],
       [  9. ,  10. ,  11. ],
       [ 12. ,  13. ,  14. ],
       [  0. ,   0.5,   1. ],
       [  1.5,   2. ,   2.5],
       [  3. ,   3.5,   4. ],
       [  4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ]])

In [36]:
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [39]:
h > 8


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [40]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
(h > 4) & (h <= 12)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]], dtype=bool)

In [42]:
h[(h < 4) | (h >= 12)]

array([ 0,  1,  2,  3, 12, 13, 14])

In [43]:
np.where(h > 7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
np.where(h % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']],
      dtype='<U4')

In [47]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
dt


dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [48]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'], 'formats': 'O int float int,int'.split()})
dt


dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [50]:
s = np.array([('Smith', 45, 1.83, (0, 1)),('Jones', 53, 1.72, (2, 2))], dtype=dt)
s

array([('Smith', 45,  1.83, (0, 1)), ('Jones', 53,  1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [53]:
s['Name'], s['Age']

(array(['Smith', 'Jones'], dtype=object), array([45, 53]))

In [54]:
s[0]

('Smith', 45,  1.83, (0, 1))

In [55]:
s['Height'].mean()

1.7749999999999999

In [56]:
np.random.seed(100)          
r = np.arange(12).reshape((4, 3))            
s = np.arange(12).reshape((4, 3)) * 0.5

In [58]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
s

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5]])

In [60]:
r+s

array([[  0. ,   1.5,   3. ],
       [  4.5,   6. ,   7.5],
       [  9. ,  10.5,  12. ],
       [ 13.5,  15. ,  16.5]])

In [61]:
2 * r + 3


array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [62]:
def f(x):              
    return 3 * x + 5

In [63]:
f(0.5)

6.5

In [64]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

In [65]:
x = np.random.standard_normal((1000000, 5))

In [66]:
y = 2 * x + 3

In [67]:
C = np.array((x, y), order='C')

In [68]:
F = np.array((x, y), order='F')

In [69]:
x = 0.0; y = 0.0

In [70]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ..., 
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ..., 
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [71]:
%timeit C.sum()

4.94 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
%timeit F.sum()

5 ms ± 336 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [73]:
%timeit C.sum(axis=0)

30.6 ms ± 5.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [74]:
%timeit F.sum(axis=1)

61.5 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
F[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ..., 
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ..., 
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])