In [ ]:
import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [6]:
a = np.arange(0, 10, 0.2)
a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [ ]:
a[:5]

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [11]:
a.sum()

245.00000000000003

In [12]:
a.std()

2.8861739379323628

In [1]:
a.cumsum(), a.std(), a.sum()

NameError: name 'a' is not defined